version: '3.8'

networks:
  nas_core_net:
    external: true

services:
  infra-filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: nas_filebrowser
    restart: always
    networks:
      - nas_core_net
    ports:
      - "8082:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - ./nas_data:/srv
      - ./filebrowser.db:/database.db

  infra-portainer:
    image: portainer/portainer-ce:latest
    container_name: nas_portainer
    restart: always
    networks:
      - nas_core_net
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    environment:
      - PORTAINER_NO_SETUP_TOKEN=1
