networks:
  nas_core_net:
    external: true

services:
  # 외부 접속 및 HTTPS 암호화를 총괄하는 Nginx Proxy Manager
  infra-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nas_proxy
    restart: always
    networks:
      - nas_core_net
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./proxy_data:/data
      - ./letsencrypt:/etc/letsencrypt

  # 초경량 웹 파일 탐색기 (Filebrowser)
  infra-filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: nas_filebrowser
    restart: always
    networks:
      - nas_core_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - ./nas_data:/srv
      - ./filebrowser.db:/filebrowser.db

  # 도커 관리 대시보드 (Portainer)
  infra-portainer:
    image: portainer/portainer-ce:latest
    container_name: nas_portainer
    restart: always
    networks:
      - nas_core_net
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    environment:
      - PORTAINER_NO_SETUP_TOKEN=1
