networks:
  nas_core_net:
    external: true

services:
  face-auth-service:
    image: pytorch/pytorch:latest
    container_name: face_auth_ai
    restart: always
    networks:
      - nas_core_net
    ports:
      - "5000:5000"
    privileged: true # 미니 PC 본체 전원 차단을 위한 커널 마스터 권한
    volumes:
      - ./face_auth_app:/app
      - ./face_data:/app/face_data
    working_dir: /app
    environment:
      - MASTER_PASSWORD=${MASTER_PASSWORD}
    command: sh -c "pip install -r requirements.txt && python app.py"
